
// Local Host:

### Retrieve all contacts 
GET http://localhost:3000 HTTP/1.1

### Create a new contact
POST http://localhost:3000/newContact HTTP/1.1
content-type: application/json

{
    "firstName": "Luna",
    "lastName": "Lovegood",
    "email": "nargles@gmail.com",
    "favoriteColor": "purple",
    "birthday": "February 15, 1981"
}

### Update the new contact (change id)
PUT http://localhost:3000/updateContact/65b43fcacd65e046a1a0f15e HTTP/1.1

### Delete the new client (change id)
DELETE http://localhost:3000/deleteContact/65b43fcacd65e046a1a0f15e HTTP/1.1


// Render

### Retrieve all contacts
GET https://boomlastclass-project.onrender.com HTTP/1.1


### Create a new contact
POST https://boomlastclass-project.onrender.com/newContact HTTP/1.1
content-type: application/json

{
    "firstName": "Luna",
    "lastName": "Lovegood",
    "email": "nargles@gmail.com",
    "favoriteColor": "purple",
    "birthday": "February 15, 1981"
}

### Update the new contact (change id)
PUT https://boomlastclass-project.onrender.com/updateContact/65b43b4ddf5f4ce674c69032 HTTP/1.1

### Delete the new client (change id)
DELETE https://boomlastclass-project.onrender.com/deleteContact/65b43b4ddf5f4ce674c69032 HTTP/1.1
